# deployments/ml-service.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ml-service
  template:
    metadata:
      labels:
        app: ml-service
    spec:
      containers:
        - name: python-ml
          image: python-ml-service:latest
          ports:
            - containerPort: 5000
        - name: go-gateway
          image: go-gateway:latest
          ports:
            - containerPort: 8080
