# Using Go 1.21+ and Python 3.10+
# Install shared dependencies
brew install protobuf  # For cross-language serialization

# Python requirements
pip install mlflow fastapi uvicorn scikit-learn

# Go modules
go get github.com/prometheus/client_golang
go get google.golang.org/grpc