# .github/workflows/build.yml
name: MLOps Pipeline

on: [push]

jobs:
  build-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      - run: make build-go
      - uses: docker/build-push-action@v3
        with:
          tags: my-registry/go-service:latest

  train-ml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: pip install -r python/requirements.txt
      - run: python python/training/train.py

  deploy:
    needs: [build-go, train-ml]
    runs-on: ubuntu-latest
    steps:
      - uses: azure/k8s-deploy@v1
        with:
          manifests: ./deployments/*
